apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-chk-ip
  labels:
    app: deploy-chk-ip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy-chk-ip
  template:
    metadata:
      labels:
        app: deploy-chk-ip
    spec:
      containers:
        - name: chk-ip
          image: 10.1.1.251:443/admin/chk-ip:1.0
      imagePullSecrets:
        - name: secret-code
